namespace fbs;

table InvalidationRequest {
  key: string;
}

table StartRequest {
  id: string;
}

table EndRequest {
  id: string;
  args: uint32;
  caller: string;
  deps: [string];
  resp: [ubyte];
}

table ManagerSaveRequest {
  key: string;
  resp: [ubyte];
}

table ManagerInvalidateRequest {
    key: string;
}

union RequestUnion {
    InvalidationRequest,
    StartRequest,
    EndRequest,
    ManagerSaveRequest,
    ManagerInvalidateRequest
}

table Request {
    request: RequestUnion;
}
root_type Request;