[package]
name = "transienta"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
lru = "0.16.1"
redis = "0.32.7"
serde = "1.0.228"
serde_yaml = "0.9.34"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "validation_benchmark"
harness = false
test = true
