// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type InvalidationRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsInvalidationRequest(buf []byte, offset flatbuffers.UOffsetT) *InvalidationRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &InvalidationRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishInvalidationRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsInvalidationRequest(buf []byte, offset flatbuffers.UOffsetT) *InvalidationRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &InvalidationRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedInvalidationRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *InvalidationRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *InvalidationRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *InvalidationRequest) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func InvalidationRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func InvalidationRequestAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func InvalidationRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
