// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ManagerInvalidateRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsManagerInvalidateRequest(buf []byte, offset flatbuffers.UOffsetT) *ManagerInvalidateRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ManagerInvalidateRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishManagerInvalidateRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsManagerInvalidateRequest(buf []byte, offset flatbuffers.UOffsetT) *ManagerInvalidateRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ManagerInvalidateRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedManagerInvalidateRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ManagerInvalidateRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ManagerInvalidateRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ManagerInvalidateRequest) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ManagerInvalidateRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ManagerInvalidateRequestAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func ManagerInvalidateRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
