// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import "strconv"

type RequestType byte

const (
	RequestTypeStart        RequestType = 0
	RequestTypeInvalidation RequestType = 1
	RequestTypeEnd          RequestType = 2
)

var EnumNamesRequestType = map[RequestType]string{
	RequestTypeStart:        "Start",
	RequestTypeInvalidation: "Invalidation",
	RequestTypeEnd:          "End",
}

var EnumValuesRequestType = map[string]RequestType{
	"Start":        RequestTypeStart,
	"Invalidation": RequestTypeInvalidation,
	"End":          RequestTypeEnd,
}

func (v RequestType) String() string {
	if s, ok := EnumNamesRequestType[v]; ok {
		return s
	}
	return "RequestType(" + strconv.FormatInt(int64(v), 10) + ")"
}
