// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import "strconv"

type RequestUnion byte

const (
	RequestUnionNONE                     RequestUnion = 0
	RequestUnionInvalidationRequest      RequestUnion = 1
	RequestUnionStartRequest             RequestUnion = 2
	RequestUnionEndRequest               RequestUnion = 3
	RequestUnionManagerSaveRequest       RequestUnion = 4
	RequestUnionManagerInvalidateRequest RequestUnion = 5
)

var EnumNamesRequestUnion = map[RequestUnion]string{
	RequestUnionNONE:                     "NONE",
	RequestUnionInvalidationRequest:      "InvalidationRequest",
	RequestUnionStartRequest:             "StartRequest",
	RequestUnionEndRequest:               "EndRequest",
	RequestUnionManagerSaveRequest:       "ManagerSaveRequest",
	RequestUnionManagerInvalidateRequest: "ManagerInvalidateRequest",
}

var EnumValuesRequestUnion = map[string]RequestUnion{
	"NONE":                     RequestUnionNONE,
	"InvalidationRequest":      RequestUnionInvalidationRequest,
	"StartRequest":             RequestUnionStartRequest,
	"EndRequest":               RequestUnionEndRequest,
	"ManagerSaveRequest":       RequestUnionManagerSaveRequest,
	"ManagerInvalidateRequest": RequestUnionManagerInvalidateRequest,
}

func (v RequestUnion) String() string {
	if s, ok := EnumNamesRequestUnion[v]; ok {
		return s
	}
	return "RequestUnion(" + strconv.FormatInt(int64(v), 10) + ")"
}
