// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StartRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsStartRequest(buf []byte, offset flatbuffers.UOffsetT) *StartRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StartRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsStartRequest(buf []byte, offset flatbuffers.UOffsetT) *StartRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StartRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *StartRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StartRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StartRequest) Number() RequestType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return RequestType(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *StartRequest) MutateNumber(n RequestType) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *StartRequest) Args() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StartRequest) MutateArgs(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func StartRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func StartRequestAddNumber(builder *flatbuffers.Builder, number RequestType) {
	builder.PrependByteSlot(0, byte(number), 0)
}
func StartRequestAddArgs(builder *flatbuffers.Builder, args uint32) {
	builder.PrependUint32Slot(1, args, 0)
}
func StartRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
