// automatically generated by the FlatBuffers compiler, do not modify

// @generated

use core::cmp::Ordering;
use core::mem;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod fbs {

    use core::cmp::Ordering;
    use core::mem;

    extern crate flatbuffers;
    use self::flatbuffers::{EndianScalar, Follow};

    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    pub const ENUM_MIN_REQUEST_UNION: u8 = 0;
    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    pub const ENUM_MAX_REQUEST_UNION: u8 = 5;
    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    #[allow(non_camel_case_types)]
    pub const ENUM_VALUES_REQUEST_UNION: [RequestUnion; 6] = [
        RequestUnion::NONE,
        RequestUnion::InvalidationRequest,
        RequestUnion::StartRequest,
        RequestUnion::EndRequest,
        RequestUnion::ManagerSaveRequest,
        RequestUnion::ManagerInvalidateRequest,
    ];

    #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
    #[repr(transparent)]
    pub struct RequestUnion(pub u8);
    #[allow(non_upper_case_globals)]
    impl RequestUnion {
        pub const NONE: Self = Self(0);
        pub const InvalidationRequest: Self = Self(1);
        pub const StartRequest: Self = Self(2);
        pub const EndRequest: Self = Self(3);
        pub const ManagerSaveRequest: Self = Self(4);
        pub const ManagerInvalidateRequest: Self = Self(5);

        pub const ENUM_MIN: u8 = 0;
        pub const ENUM_MAX: u8 = 5;
        pub const ENUM_VALUES: &'static [Self] = &[
            Self::NONE,
            Self::InvalidationRequest,
            Self::StartRequest,
            Self::EndRequest,
            Self::ManagerSaveRequest,
            Self::ManagerInvalidateRequest,
        ];
        /// Returns the variant's name or "" if unknown.
        pub fn variant_name(self) -> Option<&'static str> {
            match self {
                Self::NONE => Some("NONE"),
                Self::InvalidationRequest => Some("InvalidationRequest"),
                Self::StartRequest => Some("StartRequest"),
                Self::EndRequest => Some("EndRequest"),
                Self::ManagerSaveRequest => Some("ManagerSaveRequest"),
                Self::ManagerInvalidateRequest => Some("ManagerInvalidateRequest"),
                _ => None,
            }
        }
    }
    impl core::fmt::Debug for RequestUnion {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            if let Some(name) = self.variant_name() {
                f.write_str(name)
            } else {
                f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
            }
        }
    }
    impl<'a> flatbuffers::Follow<'a> for RequestUnion {
        type Inner = Self;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            let b = unsafe { flatbuffers::read_scalar_at::<u8>(buf, loc) };
            Self(b)
        }
    }

    impl flatbuffers::Push for RequestUnion {
        type Output = RequestUnion;
        #[inline]
        unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
            unsafe {
                flatbuffers::emplace_scalar::<u8>(dst, self.0);
            }
        }
    }

    impl flatbuffers::EndianScalar for RequestUnion {
        type Scalar = u8;
        #[inline]
        fn to_little_endian(self) -> u8 {
            self.0.to_le()
        }
        #[inline]
        #[allow(clippy::wrong_self_convention)]
        fn from_little_endian(v: u8) -> Self {
            let b = u8::from_le(v);
            Self(b)
        }
    }

    impl<'a> flatbuffers::Verifiable for RequestUnion {
        #[inline]
        fn run_verifier(
            v: &mut flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
            use self::flatbuffers::Verifiable;
            u8::run_verifier(v, pos)
        }
    }

    impl flatbuffers::SimpleToVerifyInSlice for RequestUnion {}
    pub struct RequestUnionUnionTableOffset {}

    pub enum InvalidationRequestOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct InvalidationRequest<'a> {
        pub _tab: flatbuffers::Table<'a>,
    }

    impl<'a> flatbuffers::Follow<'a> for InvalidationRequest<'a> {
        type Inner = InvalidationRequest<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: unsafe { flatbuffers::Table::new(buf, loc) },
            }
        }
    }

    impl<'a> InvalidationRequest<'a> {
        pub const VT_KEY: flatbuffers::VOffsetT = 4;

        #[inline]
        pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
            InvalidationRequest { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args InvalidationRequestArgs<'args>,
        ) -> flatbuffers::WIPOffset<InvalidationRequest<'bldr>> {
            let mut builder = InvalidationRequestBuilder::new(_fbb);
            if let Some(x) = args.key {
                builder.add_key(x);
            }
            builder.finish()
        }

        #[inline]
        pub fn key(&self) -> Option<&'a str> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<flatbuffers::ForwardsUOffset<&str>>(InvalidationRequest::VT_KEY, None)
            }
        }
    }

    impl flatbuffers::Verifiable for InvalidationRequest<'_> {
        #[inline]
        fn run_verifier(
            v: &mut flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
            use self::flatbuffers::Verifiable;
            v.visit_table(pos)?
                .visit_field::<flatbuffers::ForwardsUOffset<&str>>("key", Self::VT_KEY, false)?
                .finish();
            Ok(())
        }
    }
    pub struct InvalidationRequestArgs<'a> {
        pub key: Option<flatbuffers::WIPOffset<&'a str>>,
    }
    impl<'a> Default for InvalidationRequestArgs<'a> {
        #[inline]
        fn default() -> Self {
            InvalidationRequestArgs { key: None }
        }
    }

    pub struct InvalidationRequestBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
        fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> InvalidationRequestBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_key(&mut self, key: flatbuffers::WIPOffset<&'b str>) {
            self.fbb_
                .push_slot_always::<flatbuffers::WIPOffset<_>>(InvalidationRequest::VT_KEY, key);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> InvalidationRequestBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            InvalidationRequestBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> flatbuffers::WIPOffset<InvalidationRequest<'a>> {
            let o = self.fbb_.end_table(self.start_);
            flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl core::fmt::Debug for InvalidationRequest<'_> {
        fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
            let mut ds = f.debug_struct("InvalidationRequest");
            ds.field("key", &self.key());
            ds.finish()
        }
    }
    pub enum StartRequestOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct StartRequest<'a> {
        pub _tab: flatbuffers::Table<'a>,
    }

    impl<'a> flatbuffers::Follow<'a> for StartRequest<'a> {
        type Inner = StartRequest<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: unsafe { flatbuffers::Table::new(buf, loc) },
            }
        }
    }

    impl<'a> StartRequest<'a> {
        pub const VT_ID: flatbuffers::VOffsetT = 4;

        #[inline]
        pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
            StartRequest { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args StartRequestArgs<'args>,
        ) -> flatbuffers::WIPOffset<StartRequest<'bldr>> {
            let mut builder = StartRequestBuilder::new(_fbb);
            if let Some(x) = args.id {
                builder.add_id(x);
            }
            builder.finish()
        }

        #[inline]
        pub fn id(&self) -> Option<&'a str> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<flatbuffers::ForwardsUOffset<&str>>(StartRequest::VT_ID, None)
            }
        }
    }

    impl flatbuffers::Verifiable for StartRequest<'_> {
        #[inline]
        fn run_verifier(
            v: &mut flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
            use self::flatbuffers::Verifiable;
            v.visit_table(pos)?
                .visit_field::<flatbuffers::ForwardsUOffset<&str>>("id", Self::VT_ID, false)?
                .finish();
            Ok(())
        }
    }
    pub struct StartRequestArgs<'a> {
        pub id: Option<flatbuffers::WIPOffset<&'a str>>,
    }
    impl<'a> Default for StartRequestArgs<'a> {
        #[inline]
        fn default() -> Self {
            StartRequestArgs { id: None }
        }
    }

    pub struct StartRequestBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
        fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> StartRequestBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_id(&mut self, id: flatbuffers::WIPOffset<&'b str>) {
            self.fbb_
                .push_slot_always::<flatbuffers::WIPOffset<_>>(StartRequest::VT_ID, id);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> StartRequestBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            StartRequestBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> flatbuffers::WIPOffset<StartRequest<'a>> {
            let o = self.fbb_.end_table(self.start_);
            flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl core::fmt::Debug for StartRequest<'_> {
        fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
            let mut ds = f.debug_struct("StartRequest");
            ds.field("id", &self.id());
            ds.finish()
        }
    }
    pub enum EndRequestOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct EndRequest<'a> {
        pub _tab: flatbuffers::Table<'a>,
    }

    impl<'a> flatbuffers::Follow<'a> for EndRequest<'a> {
        type Inner = EndRequest<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: unsafe { flatbuffers::Table::new(buf, loc) },
            }
        }
    }

    impl<'a> EndRequest<'a> {
        pub const VT_ID: flatbuffers::VOffsetT = 4;
        pub const VT_ARGS: flatbuffers::VOffsetT = 6;
        pub const VT_CALLER: flatbuffers::VOffsetT = 8;
        pub const VT_DEPS: flatbuffers::VOffsetT = 10;
        pub const VT_RESP: flatbuffers::VOffsetT = 12;

        #[inline]
        pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
            EndRequest { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args EndRequestArgs<'args>,
        ) -> flatbuffers::WIPOffset<EndRequest<'bldr>> {
            let mut builder = EndRequestBuilder::new(_fbb);
            if let Some(x) = args.resp {
                builder.add_resp(x);
            }
            if let Some(x) = args.deps {
                builder.add_deps(x);
            }
            if let Some(x) = args.caller {
                builder.add_caller(x);
            }
            builder.add_args(args.args);
            if let Some(x) = args.id {
                builder.add_id(x);
            }
            builder.finish()
        }

        #[inline]
        pub fn id(&self) -> Option<&'a str> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<flatbuffers::ForwardsUOffset<&str>>(EndRequest::VT_ID, None)
            }
        }
        #[inline]
        pub fn args(&self) -> u32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<u32>(EndRequest::VT_ARGS, Some(0)).unwrap() }
        }
        #[inline]
        pub fn caller(&self) -> Option<&'a str> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<flatbuffers::ForwardsUOffset<&str>>(EndRequest::VT_CALLER, None)
            }
        }
        #[inline]
        pub fn deps(
            &self,
        ) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab.get::<flatbuffers::ForwardsUOffset<
                    flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>,
                >>(EndRequest::VT_DEPS, None)
            }
        }
        #[inline]
        pub fn resp(&self) -> Option<flatbuffers::Vector<'a, u8>> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(
                        EndRequest::VT_RESP,
                        None,
                    )
            }
        }
    }

    impl flatbuffers::Verifiable for EndRequest<'_> {
        #[inline]
        fn run_verifier(
            v: &mut flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
            use self::flatbuffers::Verifiable;
            v.visit_table(pos)?
                .visit_field::<flatbuffers::ForwardsUOffset<&str>>("id", Self::VT_ID, false)?
                .visit_field::<u32>("args", Self::VT_ARGS, false)?
                .visit_field::<flatbuffers::ForwardsUOffset<&str>>(
                    "caller",
                    Self::VT_CALLER,
                    false,
                )?
                .visit_field::<flatbuffers::ForwardsUOffset<
                    flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<&'_ str>>,
                >>("deps", Self::VT_DEPS, false)?
                .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>(
                    "resp",
                    Self::VT_RESP,
                    false,
                )?
                .finish();
            Ok(())
        }
    }
    pub struct EndRequestArgs<'a> {
        pub id: Option<flatbuffers::WIPOffset<&'a str>>,
        pub args: u32,
        pub caller: Option<flatbuffers::WIPOffset<&'a str>>,
        pub deps: Option<
            flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>>,
        >,
        pub resp: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    }
    impl<'a> Default for EndRequestArgs<'a> {
        #[inline]
        fn default() -> Self {
            EndRequestArgs {
                id: None,
                args: 0,
                caller: None,
                deps: None,
                resp: None,
            }
        }
    }

    pub struct EndRequestBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
        fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> EndRequestBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_id(&mut self, id: flatbuffers::WIPOffset<&'b str>) {
            self.fbb_
                .push_slot_always::<flatbuffers::WIPOffset<_>>(EndRequest::VT_ID, id);
        }
        #[inline]
        pub fn add_args(&mut self, args: u32) {
            self.fbb_.push_slot::<u32>(EndRequest::VT_ARGS, args, 0);
        }
        #[inline]
        pub fn add_caller(&mut self, caller: flatbuffers::WIPOffset<&'b str>) {
            self.fbb_
                .push_slot_always::<flatbuffers::WIPOffset<_>>(EndRequest::VT_CALLER, caller);
        }
        #[inline]
        pub fn add_deps(
            &mut self,
            deps: flatbuffers::WIPOffset<
                flatbuffers::Vector<'b, flatbuffers::ForwardsUOffset<&'b str>>,
            >,
        ) {
            self.fbb_
                .push_slot_always::<flatbuffers::WIPOffset<_>>(EndRequest::VT_DEPS, deps);
        }
        #[inline]
        pub fn add_resp(&mut self, resp: flatbuffers::WIPOffset<flatbuffers::Vector<'b, u8>>) {
            self.fbb_
                .push_slot_always::<flatbuffers::WIPOffset<_>>(EndRequest::VT_RESP, resp);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> EndRequestBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            EndRequestBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> flatbuffers::WIPOffset<EndRequest<'a>> {
            let o = self.fbb_.end_table(self.start_);
            flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl core::fmt::Debug for EndRequest<'_> {
        fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
            let mut ds = f.debug_struct("EndRequest");
            ds.field("id", &self.id());
            ds.field("args", &self.args());
            ds.field("caller", &self.caller());
            ds.field("deps", &self.deps());
            ds.field("resp", &self.resp());
            ds.finish()
        }
    }
    pub enum ManagerSaveRequestOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct ManagerSaveRequest<'a> {
        pub _tab: flatbuffers::Table<'a>,
    }

    impl<'a> flatbuffers::Follow<'a> for ManagerSaveRequest<'a> {
        type Inner = ManagerSaveRequest<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: unsafe { flatbuffers::Table::new(buf, loc) },
            }
        }
    }

    impl<'a> ManagerSaveRequest<'a> {
        pub const VT_KEY: flatbuffers::VOffsetT = 4;
        pub const VT_RESP: flatbuffers::VOffsetT = 6;

        #[inline]
        pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
            ManagerSaveRequest { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args ManagerSaveRequestArgs<'args>,
        ) -> flatbuffers::WIPOffset<ManagerSaveRequest<'bldr>> {
            let mut builder = ManagerSaveRequestBuilder::new(_fbb);
            if let Some(x) = args.resp {
                builder.add_resp(x);
            }
            if let Some(x) = args.key {
                builder.add_key(x);
            }
            builder.finish()
        }

        #[inline]
        pub fn key(&self) -> Option<&'a str> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<flatbuffers::ForwardsUOffset<&str>>(ManagerSaveRequest::VT_KEY, None)
            }
        }
        #[inline]
        pub fn resp(&self) -> Option<flatbuffers::Vector<'a, u8>> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(
                        ManagerSaveRequest::VT_RESP,
                        None,
                    )
            }
        }
    }

    impl flatbuffers::Verifiable for ManagerSaveRequest<'_> {
        #[inline]
        fn run_verifier(
            v: &mut flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
            use self::flatbuffers::Verifiable;
            v.visit_table(pos)?
                .visit_field::<flatbuffers::ForwardsUOffset<&str>>("key", Self::VT_KEY, false)?
                .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>(
                    "resp",
                    Self::VT_RESP,
                    false,
                )?
                .finish();
            Ok(())
        }
    }
    pub struct ManagerSaveRequestArgs<'a> {
        pub key: Option<flatbuffers::WIPOffset<&'a str>>,
        pub resp: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    }
    impl<'a> Default for ManagerSaveRequestArgs<'a> {
        #[inline]
        fn default() -> Self {
            ManagerSaveRequestArgs {
                key: None,
                resp: None,
            }
        }
    }

    pub struct ManagerSaveRequestBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
        fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> ManagerSaveRequestBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_key(&mut self, key: flatbuffers::WIPOffset<&'b str>) {
            self.fbb_
                .push_slot_always::<flatbuffers::WIPOffset<_>>(ManagerSaveRequest::VT_KEY, key);
        }
        #[inline]
        pub fn add_resp(&mut self, resp: flatbuffers::WIPOffset<flatbuffers::Vector<'b, u8>>) {
            self.fbb_
                .push_slot_always::<flatbuffers::WIPOffset<_>>(ManagerSaveRequest::VT_RESP, resp);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> ManagerSaveRequestBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            ManagerSaveRequestBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> flatbuffers::WIPOffset<ManagerSaveRequest<'a>> {
            let o = self.fbb_.end_table(self.start_);
            flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl core::fmt::Debug for ManagerSaveRequest<'_> {
        fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
            let mut ds = f.debug_struct("ManagerSaveRequest");
            ds.field("key", &self.key());
            ds.field("resp", &self.resp());
            ds.finish()
        }
    }
    pub enum ManagerInvalidateRequestOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct ManagerInvalidateRequest<'a> {
        pub _tab: flatbuffers::Table<'a>,
    }

    impl<'a> flatbuffers::Follow<'a> for ManagerInvalidateRequest<'a> {
        type Inner = ManagerInvalidateRequest<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: unsafe { flatbuffers::Table::new(buf, loc) },
            }
        }
    }

    impl<'a> ManagerInvalidateRequest<'a> {
        pub const VT_KEY: flatbuffers::VOffsetT = 4;

        #[inline]
        pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
            ManagerInvalidateRequest { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args ManagerInvalidateRequestArgs<'args>,
        ) -> flatbuffers::WIPOffset<ManagerInvalidateRequest<'bldr>> {
            let mut builder = ManagerInvalidateRequestBuilder::new(_fbb);
            if let Some(x) = args.key {
                builder.add_key(x);
            }
            builder.finish()
        }

        #[inline]
        pub fn key(&self) -> Option<&'a str> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(
                    ManagerInvalidateRequest::VT_KEY,
                    None,
                )
            }
        }
    }

    impl flatbuffers::Verifiable for ManagerInvalidateRequest<'_> {
        #[inline]
        fn run_verifier(
            v: &mut flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
            use self::flatbuffers::Verifiable;
            v.visit_table(pos)?
                .visit_field::<flatbuffers::ForwardsUOffset<&str>>("key", Self::VT_KEY, false)?
                .finish();
            Ok(())
        }
    }
    pub struct ManagerInvalidateRequestArgs<'a> {
        pub key: Option<flatbuffers::WIPOffset<&'a str>>,
    }
    impl<'a> Default for ManagerInvalidateRequestArgs<'a> {
        #[inline]
        fn default() -> Self {
            ManagerInvalidateRequestArgs { key: None }
        }
    }

    pub struct ManagerInvalidateRequestBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
        fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> ManagerInvalidateRequestBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_key(&mut self, key: flatbuffers::WIPOffset<&'b str>) {
            self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
                ManagerInvalidateRequest::VT_KEY,
                key,
            );
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> ManagerInvalidateRequestBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            ManagerInvalidateRequestBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> flatbuffers::WIPOffset<ManagerInvalidateRequest<'a>> {
            let o = self.fbb_.end_table(self.start_);
            flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl core::fmt::Debug for ManagerInvalidateRequest<'_> {
        fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
            let mut ds = f.debug_struct("ManagerInvalidateRequest");
            ds.field("key", &self.key());
            ds.finish()
        }
    }
    pub enum RequestOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct Request<'a> {
        pub _tab: flatbuffers::Table<'a>,
    }

    impl<'a> flatbuffers::Follow<'a> for Request<'a> {
        type Inner = Request<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: unsafe { flatbuffers::Table::new(buf, loc) },
            }
        }
    }

    impl<'a> Request<'a> {
        pub const VT_REQUEST_TYPE: flatbuffers::VOffsetT = 4;
        pub const VT_REQUEST: flatbuffers::VOffsetT = 6;

        #[inline]
        pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
            Request { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args RequestArgs,
        ) -> flatbuffers::WIPOffset<Request<'bldr>> {
            let mut builder = RequestBuilder::new(_fbb);
            if let Some(x) = args.request {
                builder.add_request(x);
            }
            builder.add_request_type(args.request_type);
            builder.finish()
        }

        #[inline]
        pub fn request_type(&self) -> RequestUnion {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<RequestUnion>(Request::VT_REQUEST_TYPE, Some(RequestUnion::NONE))
                    .unwrap()
            }
        }
        #[inline]
        pub fn request(&self) -> Option<flatbuffers::Table<'a>> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<flatbuffers::ForwardsUOffset<flatbuffers::Table<'a>>>(
                        Request::VT_REQUEST,
                        None,
                    )
            }
        }
        #[inline]
        #[allow(non_snake_case)]
        pub fn request_as_invalidation_request(&self) -> Option<InvalidationRequest<'a>> {
            if self.request_type() == RequestUnion::InvalidationRequest {
                self.request().map(|t| {
                    // Safety:
                    // Created from a valid Table for this object
                    // Which contains a valid union in this slot
                    unsafe { InvalidationRequest::init_from_table(t) }
                })
            } else {
                None
            }
        }

        #[inline]
        #[allow(non_snake_case)]
        pub fn request_as_start_request(&self) -> Option<StartRequest<'a>> {
            if self.request_type() == RequestUnion::StartRequest {
                self.request().map(|t| {
                    // Safety:
                    // Created from a valid Table for this object
                    // Which contains a valid union in this slot
                    unsafe { StartRequest::init_from_table(t) }
                })
            } else {
                None
            }
        }

        #[inline]
        #[allow(non_snake_case)]
        pub fn request_as_end_request(&self) -> Option<EndRequest<'a>> {
            if self.request_type() == RequestUnion::EndRequest {
                self.request().map(|t| {
                    // Safety:
                    // Created from a valid Table for this object
                    // Which contains a valid union in this slot
                    unsafe { EndRequest::init_from_table(t) }
                })
            } else {
                None
            }
        }

        #[inline]
        #[allow(non_snake_case)]
        pub fn request_as_manager_save_request(&self) -> Option<ManagerSaveRequest<'a>> {
            if self.request_type() == RequestUnion::ManagerSaveRequest {
                self.request().map(|t| {
                    // Safety:
                    // Created from a valid Table for this object
                    // Which contains a valid union in this slot
                    unsafe { ManagerSaveRequest::init_from_table(t) }
                })
            } else {
                None
            }
        }

        #[inline]
        #[allow(non_snake_case)]
        pub fn request_as_manager_invalidate_request(
            &self,
        ) -> Option<ManagerInvalidateRequest<'a>> {
            if self.request_type() == RequestUnion::ManagerInvalidateRequest {
                self.request().map(|t| {
                    // Safety:
                    // Created from a valid Table for this object
                    // Which contains a valid union in this slot
                    unsafe { ManagerInvalidateRequest::init_from_table(t) }
                })
            } else {
                None
            }
        }
    }

    impl flatbuffers::Verifiable for Request<'_> {
        #[inline]
        fn run_verifier(
            v: &mut flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
            use self::flatbuffers::Verifiable;
            v.visit_table(pos)?
     .visit_union::<RequestUnion, _>("request_type", Self::VT_REQUEST_TYPE, "request", Self::VT_REQUEST, false, |key, v, pos| {
        match key {
          RequestUnion::InvalidationRequest => v.verify_union_variant::<flatbuffers::ForwardsUOffset<InvalidationRequest>>("RequestUnion::InvalidationRequest", pos),
          RequestUnion::StartRequest => v.verify_union_variant::<flatbuffers::ForwardsUOffset<StartRequest>>("RequestUnion::StartRequest", pos),
          RequestUnion::EndRequest => v.verify_union_variant::<flatbuffers::ForwardsUOffset<EndRequest>>("RequestUnion::EndRequest", pos),
          RequestUnion::ManagerSaveRequest => v.verify_union_variant::<flatbuffers::ForwardsUOffset<ManagerSaveRequest>>("RequestUnion::ManagerSaveRequest", pos),
          RequestUnion::ManagerInvalidateRequest => v.verify_union_variant::<flatbuffers::ForwardsUOffset<ManagerInvalidateRequest>>("RequestUnion::ManagerInvalidateRequest", pos),
          _ => Ok(()),
        }
     })?
     .finish();
            Ok(())
        }
    }
    pub struct RequestArgs {
        pub request_type: RequestUnion,
        pub request: Option<flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>>,
    }
    impl<'a> Default for RequestArgs {
        #[inline]
        fn default() -> Self {
            RequestArgs {
                request_type: RequestUnion::NONE,
                request: None,
            }
        }
    }

    pub struct RequestBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
        fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> RequestBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_request_type(&mut self, request_type: RequestUnion) {
            self.fbb_.push_slot::<RequestUnion>(
                Request::VT_REQUEST_TYPE,
                request_type,
                RequestUnion::NONE,
            );
        }
        #[inline]
        pub fn add_request(
            &mut self,
            request: flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>,
        ) {
            self.fbb_
                .push_slot_always::<flatbuffers::WIPOffset<_>>(Request::VT_REQUEST, request);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> RequestBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            RequestBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> flatbuffers::WIPOffset<Request<'a>> {
            let o = self.fbb_.end_table(self.start_);
            flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl core::fmt::Debug for Request<'_> {
        fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
            let mut ds = f.debug_struct("Request");
            ds.field("request_type", &self.request_type());
            match self.request_type() {
                RequestUnion::InvalidationRequest => {
                    if let Some(x) = self.request_as_invalidation_request() {
                        ds.field("request", &x)
                    } else {
                        ds.field(
                            "request",
                            &"InvalidFlatbuffer: Union discriminant does not match value.",
                        )
                    }
                }
                RequestUnion::StartRequest => {
                    if let Some(x) = self.request_as_start_request() {
                        ds.field("request", &x)
                    } else {
                        ds.field(
                            "request",
                            &"InvalidFlatbuffer: Union discriminant does not match value.",
                        )
                    }
                }
                RequestUnion::EndRequest => {
                    if let Some(x) = self.request_as_end_request() {
                        ds.field("request", &x)
                    } else {
                        ds.field(
                            "request",
                            &"InvalidFlatbuffer: Union discriminant does not match value.",
                        )
                    }
                }
                RequestUnion::ManagerSaveRequest => {
                    if let Some(x) = self.request_as_manager_save_request() {
                        ds.field("request", &x)
                    } else {
                        ds.field(
                            "request",
                            &"InvalidFlatbuffer: Union discriminant does not match value.",
                        )
                    }
                }
                RequestUnion::ManagerInvalidateRequest => {
                    if let Some(x) = self.request_as_manager_invalidate_request() {
                        ds.field("request", &x)
                    } else {
                        ds.field(
                            "request",
                            &"InvalidFlatbuffer: Union discriminant does not match value.",
                        )
                    }
                }
                _ => {
                    let x: Option<()> = None;
                    ds.field("request", &x)
                }
            };
            ds.finish()
        }
    }
    #[inline]
    /// Verifies that a buffer of bytes contains a `Request`
    /// and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_request_unchecked`.
    pub fn root_as_request(buf: &[u8]) -> Result<Request, flatbuffers::InvalidFlatbuffer> {
        flatbuffers::root::<Request>(buf)
    }
    #[inline]
    /// Verifies that a buffer of bytes contains a size prefixed
    /// `Request` and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `size_prefixed_root_as_request_unchecked`.
    pub fn size_prefixed_root_as_request(
        buf: &[u8],
    ) -> Result<Request, flatbuffers::InvalidFlatbuffer> {
        flatbuffers::size_prefixed_root::<Request>(buf)
    }
    #[inline]
    /// Verifies, with the given options, that a buffer of bytes
    /// contains a `Request` and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_request_unchecked`.
    pub fn root_as_request_with_opts<'b, 'o>(
        opts: &'o flatbuffers::VerifierOptions,
        buf: &'b [u8],
    ) -> Result<Request<'b>, flatbuffers::InvalidFlatbuffer> {
        flatbuffers::root_with_opts::<Request<'b>>(opts, buf)
    }
    #[inline]
    /// Verifies, with the given verifier options, that a buffer of
    /// bytes contains a size prefixed `Request` and returns
    /// it. Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_request_unchecked`.
    pub fn size_prefixed_root_as_request_with_opts<'b, 'o>(
        opts: &'o flatbuffers::VerifierOptions,
        buf: &'b [u8],
    ) -> Result<Request<'b>, flatbuffers::InvalidFlatbuffer> {
        flatbuffers::size_prefixed_root_with_opts::<Request<'b>>(opts, buf)
    }
    #[inline]
    /// Assumes, without verification, that a buffer of bytes contains a Request and returns it.
    /// # Safety
    /// Callers must trust the given bytes do indeed contain a valid `Request`.
    pub unsafe fn root_as_request_unchecked(buf: &[u8]) -> Request {
        unsafe { flatbuffers::root_unchecked::<Request>(buf) }
    }
    #[inline]
    /// Assumes, without verification, that a buffer of bytes contains a size prefixed Request and returns it.
    /// # Safety
    /// Callers must trust the given bytes do indeed contain a valid size prefixed `Request`.
    pub unsafe fn size_prefixed_root_as_request_unchecked(buf: &[u8]) -> Request {
        unsafe { flatbuffers::size_prefixed_root_unchecked::<Request>(buf) }
    }
    #[inline]
    pub fn finish_request_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
        fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        root: flatbuffers::WIPOffset<Request<'a>>,
    ) {
        fbb.finish(root, None);
    }

    #[inline]
    pub fn finish_size_prefixed_request_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
        fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        root: flatbuffers::WIPOffset<Request<'a>>,
    ) {
        fbb.finish_size_prefixed(root, None);
    }
} // pub mod fbs
